### ISSUE TITLE
Recursive `build_call_graph` does not work

### ISSUE THREAD

**Issue by matthagan15** [quantumlib/Qualtran#1063]
A "nice to have" feature would be the ability for a recursive `build_call_graph` decomposition to solve for symbolic recurrence relations if solvable.

**Comment by fdmalone** [comment]
the argument for show_call_graph is not a bloq, it's the graph returned by bloq.call_graph (e.g. https://qualtran.readthedocs.io/en/latest/bloqs/qft/two_bit_ffft.html#call-graph), if that helps.

**Comment by fdmalone** [comment]
Although I'm fairly certain this still won't work as written.

**Comment by matthagan15** [comment]
Thanks that was the issue, managed to get it working even with symbolics. @tanujkhattar had mentioned it might be possible to use sympy's symbolic solvers to try and see if a recurrence relation could be solved to give an estimate for the resources used if the recurrence is solvable.

**Comment by fdmalone** [comment]
cool
