### ISSUE TITLE
Bitlength of "keep" and "alt" probabilities in coherent alias sampling

### ISSUE THREAD

**Issue by christoph-riverlane** [quantumlib/Qualtran#1071]
Qualtran computes this as log_2(ε/n):
https://github.com/quantumlib/Qualtran/blob/0d8793e8a7f415d6ec1e003756422d72ac81a3a1/qualtran/linalg/lcu_util.py#L161
and does not make any reference to λ (the 1-norm / subnormalisation).

However, this doesn't match the papers:
*  Eq. (36) in "Encoding Electronic Spectra in Quantum Circuits with Linear T Complexity" has a different formula with dependence on λ.
* Eq. (A12) in the Tensor Hypercontraction paper also has a formula for the bit length of the keep probabilities that makes reference to λ.

Tagging @tanujkhattar whom I briefly discussed this inconsistency with at the Qualtran workshop last Friday

**Comment by tanujkhattar** [comment]
@anurudhp Since you are working on extending state preparation alias sampling, can you take this one as well?

**Comment by anurudhp** [comment]
Let me take a look
