### ISSUE TITLE
Improve support for QFxp in classical simulation

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Qualtran#1095]
Classical simulation protocol assumes values are always integer as seen by the type hint https://github.com/quantumlib/Qualtran/blob/c6aa41980b6d27a9a1395448dbcab297b87540f7/qualtran/simulation/classical_sim.py#L37

however float values can happen when using `QFxp` dtype.

**Comment by fdmalone** [comment]
xref #859

**Comment by anurudhp** [comment]
#1215 adds support for QDType specific values, and #1219 can be used to track ideas for classical representations of `QFxp` values.
