### ISSUE TITLE
Add support for Toffoli Complexity along with T-complexity

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#110]
Many fault-tolerant algorithm papers use either T-complexity (T-gates, cliffords and rotations) or Toffli Complexity (i.e. Toffoli gate, Cliffords and Rotations). 

A single Toffoli can be decomposed into 4 T-gates but the inverse is harder to do (combining T-gates to get Toffoli's). 

We should think about how to add support for getting both T-complexity and Toffoli complexity; and whether we should default to using Toffoli complexity instead of T-complexity.

**Comment by mpharrigan** [comment]
xref #873 #539

**Comment by mpharrigan** [comment]
This is done in `QECGatesCost` and `BloqCount` costs
