### ISSUE TITLE
Add support for `MultiControlledU` via `C-U` and `MultiAnd`

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#1131]
- [x] Generalize `MultiControlledPauli` to accept any Bloq `U` with a single-bit control.
- [x] Replace `MultiControlledX` with `MultiControlledU(XGate())`
- [ ] Return this as the default in `Bloq.controlled()`?
- [x] Document: When the user needs $\text{MC-U}^\dagger \cdot V \cdot \text{MC-U}$, they can use `MultiAnd` to compute the controls, and only uncompute at the end (instead of twice when using `MultiControlledU`)

Related: #914

**Comment by mpharrigan** [comment]
The fallback for `Bloq.controlled()` returns `qualtran.Controlled(subbloq)` meta-wrapper. For (3), I'm proposing that we switch the decomposition for `Controlled` (which right now just does a multi-controlled version of each subbloq) to use an And ladder to produce one control bit, and then do a singly-controlled version of each subbloq

**Comment by anurudhp** [comment]
this was completed in #1451 and #1456

**Comment by mpharrigan** [comment]
wooooooo
