### ISSUE TITLE
[arithmetic] add bloq variants that output their intermediate registers

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#1140]
Add a RIGHT junk register that stores the intermediate values, which can be uncomputed by the adjoint operation. Useful when the bloqs occur in compute-uncompute pairs, to avoid greedily uncomputing intermediate registers.

**Comment by NoureldinYosri** [comment]
for comparison gates, this was done in https://github.com/quantumlib/Qualtran/pull/1408

I'm closing this for now unless we need the same feature for other bloqs
