### ISSUE TITLE
`CtrlSpec` add support for symbolic `Shaped` control values

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#1168]
Useful when we know the number of controls, e.g. https://github.com/quantumlib/Qualtran/pull/1155#discussion_r1684923203

Related #786

**Comment by mpharrigan** [comment]
What is missing?

**Comment by anurudhp** [comment]
Requires some fixes to how shapes and num_qubits are computed to work with symbolics, and updated type hints. Didn't want to over-complicate #1155, so this can be done in a follow-up.

**Comment by anurudhp** [comment]
@fpapa250 this will be fixed by #1492 (which removes the call graph override and uses the default from `ControlledViaAnd`). I tested the code snippet against that branch and it prints `{'n_t': 0, 'n_ccz': n}`

**Comment by fpapa250** [comment]
Awesome! That will unblock https://github.com/quantumlib/Qualtran/pull/1489. Equals.controlled breaks down to that case and is causing issues with the symbolic cost unit test.
