### ISSUE TITLE
Add n-bit Identity, implement C[I] = I

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#1207]
We have a one qubit `Identity` bloq. This should probably let you do an n-bit identity operation and the controlled version of it should be an `n+m` bit identity for m control bits.

**Comment by mpharrigan** [comment]
I ran into this trying to do bloqs-only resource counting of ApplyGateToLthTarget where we end up with a controlled identity and need to say that it takes no T gates.

**Comment by fdmalone** [comment]
Does OnEach not capture nbit identity?

**Comment by mpharrigan** [comment]
ah I suppose it would
