### ISSUE TITLE
Should bloqs with an empty list of callees be allowed?

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#1208]
Ran into this in some of the resource counting stuff. 

In the call graph of `_state_prep_via_rotations` the following bloq is encountered

```python
    bloq = QROM(data_or_shape=(np.array([0,0]),), selection_bitsizes=(1,), target_bitsizes=(2,), target_shapes=((),), num_controls=1)
```

where

```python
get_bloq_callee_counts(bloq) == []
```

but not because QROM can't or shouldn't be decomposed -- i.e. it isn't a "leaf bloq". Rather: that configuration of parameters just yields an empty decomposition. This feels wrong to me

**Comment by tanujkhattar** [comment]
It definitely makes the call sites simpler. In other words, there can be multiple ways of specifying an identity gate and an empty circuit / bloq with an empty decomposition is one of such ways. 

I do see the problem though that it creates if we wish to enforce that "every bloq decomposition would end in a leaf bloq from `basic_gates`"

**Comment by mpharrigan** [comment]
The specific thing here was trying to simplify the gate counting logic by using `get_bloq_callee_counts`, which smooshes the two cases of "no decomposition" and "empty decomposition"; I'll un-simplify the logic in my branch.
