### ISSUE TITLE
Should we make variable spaced qrom more explicit?

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#1211]
Currently it's sort of a hidden optimization which can be triggered accidentally (xref #1210). I wonder if perhaps it should be off by default so there are no surprises, and only used when the user explicitly wants to make use of the optimization?

**Comment by fdmalone** [comment]
WDYT @tanujkhattar

**Comment by mpharrigan** [comment]
I'm generally not a fan of overly-smart optimizations but I admit I don't know exactly how the qrom bloqs figure out their early stopping behavior. 

I can imagine a world in which using e.g. a symbolic qrom uses the "generic" costs and real data will try to eek out every T gate.

But my preference would be to have a less-surprising way to trigger these types of optimizations

**Comment by fdmalone** [comment]
Yeah symbolic is probably the way to go.

**Comment by tanujkhattar** [comment]
Symbolic analysis ignores the variable spaced QROM optimization and if you provide real data; I think implementing the optimization by default is the right thing to do. 

In the specific case this got triggered; tests without a random seed were creating a problem. In a real world use case; I imagine I would want to get the best gate counts for the data I have. Having another flag to QROM means this flag would need to be passed in by every Bloq that uses a QROM (eg: state preparation, rotation synthesis etc.) and that's not great either. 

I would vote for keeping the optimization on by default and use symbolic analysis for a generic cost formula -- this is the current state of things so no change is required in the behavior.

**Comment by fdmalone** [comment]
SGTM
