### ISSUE TITLE
definition of `_add_ctrled` is too restrictive

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Qualtran#1272]
The second return return value of `get_ctrl_system` is `_add_ctrled` which is defined as
  
https://github.com/quantumlib/Qualtran/blob/a4365b26a01956bb0341f12e673176e3a66ab33b/qualtran/_infra/bloq.py#L384C33-L389

This definition is too restrictive since it assumes that no new registers may be created which is not true. for example And().controlled() should be MultiAnd which creates an extra `junk` register.

**Comment by mpharrigan** [comment]
I think this is out of scope for the notion of a "controlled" operation.

Controlled(A) = $\ket{0}\bra{0}\otimes I + \ket{1}\bra{1} \otimes A$

**Comment by mpharrigan** [comment]
@NoureldinYosri can you provide more context on your use case

**Comment by mpharrigan** [comment]
I wrote some more here: https://github.com/quantumlib/Qualtran/issues/1304#issuecomment-2307862322

The contract (irrespective of whether the registers are RIGHT or THRU) is that the controlled version can only add new registers that comport with `CtrlSpec.qdtypes`. The system has no idea what to do with the extra junk registers. If you wanted to encode the idea that "this junk needs to get cleaned up by And^dag" you'd use something like #1221
