### ISSUE TITLE
Counting rotations notes

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#1309]

**Comment by mpharrigan** [comment]
We treat Rz(pi/4) as a T gate. I'm not sure how I feel about that; but for expediency I will reproduce this behavior in the QECGatesCost cost.

However, the t_complexity protocol treats Rx(pi/4) as a rotation instead of a T and a clifford. I think we should be consistent and count these as a T gate. I'm not going to count them as a T+clifford because that complicates the code.

The Rx and Ry bloq examples use T angles. We should change them to be arbitrary angle

**Comment by mpharrigan** [comment]
LPRSInterimPrep -- its t_complexity method does not match its build_call_graph, or at least not how we usually treat it. Elsewhere, we treat a CRz as one "rotation"; here' each is treated as 2 rotations and 3 cliffords

**Comment by mpharrigan** [comment]
QvrZPow.qvr_zpow uses six ZPowGates. But the exponent is less than epsilon and my wip code treats it as six cliffords

**Comment by mpharrigan** [comment]
I think the t complexity of `QuantumVariableRotation` is very incorrect

https://github.com/quantumlib/Qualtran/blob/03d09a01f0e246bbd30573c817c60becd49f0621/qualtran/bloqs/chemistry/trotter/grid_ham/qvr.py#L61

since the 0 angle gets turned into a clifford

**Comment by mpharrigan** [comment]
LPResourceState also relies on simplifying CZ**1.0 to CZ

**Comment by mpharrigan** [comment]
https://github.com/quantumlib/Qualtran/blob/7823bdbf51e596babfd242726b5aba04d8abc93f/qualtran/bloqs/basic_gates/su2_rotation.py#L151

SU2RotationGate always returns 3 rotations, no matter the angles; even if they turn into cliffords or Ts. Indeed the bloq_examples all use angles that can be specialized.

**Comment by mpharrigan** [comment]
https://github.com/quantumlib/Qualtran/blob/ec85731ec6e0e498797b8412b39f7bdd75bc20f0/qualtran/bloqs/arithmetic/controlled_addition.py#L163

bloq_example "cmodadd_symbolic" has CAdd as one of its callees. The t complexity protocol reports the number of toffolis as $8n+4$, which would be $2n + 1$ AND's. The call graph reports n AND + 1 `Add` with $n$ ands; giving a total of $2n$ ANDs

@NoureldinYosri can you investigate

**Comment by mpharrigan** [comment]
https://github.com/quantumlib/Qualtran/blob/0f09271e6a45ed8acf020e0cce266fefbc0f6adb/qualtran/bloqs/phase_estimation/lp_resource_state.py#L171

LPResourceState uses CZPowGate(1.0) instead of just a CZ gate. Will change

**Comment by tanujkhattar** [comment]
@mpharrigan The `LPResourceState` implementation is updated as part of https://github.com/quantumlib/Qualtran/pull/1297

**Comment by mpharrigan** [comment]
What should the cost be of the state and effect bloqs. `MinusState` etc. `Allocate` and `Free` have historically returned 0 `TComplexity()`

**Comment by mpharrigan** [comment]
There's a meaningful discrepancy in the rotation count in `HamiltonianSimulationByGQSP`. The `GeneralizedQSP` bloq call graph emits a lot of SU2 rotations, which are each treated as 3 rotations in the legacy protocol but can be simplified. 

I would strongly advocate for changing the call graph method of GeneralizedQSP to give n SU2 rotations instead of listing all of the different ones. The call graph is pretty unreadable at present

**Comment by mpharrigan** [comment]
ApplyLthGate is blocked by #1207

**Comment by NoureldinYosri** [comment]
> https://github.com/quantumlib/Qualtran/blob/ec85731ec6e0e498797b8412b39f7bdd75bc20f0/qualtran/bloqs/arithmetic/controlled_addition.py#L163
> 
> bloq_example "cmodadd_symbolic" has CAdd as one of its callees. The t complexity protocol reports the number of toffolis as 8 n + 4 , which would be 2 n + 1 AND's. The call graph reports n AND + 1 `Add` with n ands; giving a total of 2 n ANDs
> 
> @NoureldinYosri can you investigate

fixed in https://github.com/quantumlib/Qualtran/pull/1329

**Comment by mpharrigan** [comment]
This is broken in `t_complexity` as well; This may have been a regression due to #1313 

`GeneralizedQSP` results in Controlled(XPowGate) with clifford angles that confuse the current (hacky) logic for Controlled(Rot). We need real CRx, CRy, CRz, CXPowGate, CYPowGate. We have CZPowGate

**Comment by mpharrigan** [comment]
scaled_chebyshev_poly_even is broken for t_complexity and gate counts because it uses `Controlled(SingleQubitCompare)` which doesn't work for the same reasons as #1271

**Comment by mpharrigan** [comment]
product_block_encoding_symb doesn't work because there is no symbolic decomposition and there is no `build_call_graph`. @charlesyuan314 can we support symbolic gate counts for product?

**Comment by mpharrigan** [comment]
`CAdd` has `build_call_graph` and `_t_complexity_` that disagree on clifford count (I think). @NoureldinYosri can you investigate and remove the _t_complexity_ method

**Comment by mpharrigan** [comment]
Other bloq examples with mismatched clifford counts

 - cmodadd_example
 - cmodadd_symbolic
 - cmodsub_symb
 - qubitization_qpe_chem_thc

that I haven't investigated yet

**Comment by NoureldinYosri** [comment]
> `CAdd` has `build_call_graph` and `_t_complexity_` that disagree on clifford count (I think). @NoureldinYosri can you investigate and remove the _t_complexity_ method

it's okay to remove it ... it was written for an old decomposition and had to be fixed before.

**Comment by mpharrigan** [comment]
These are all fixed
