### ISSUE TITLE
`build_composite_bloq` is not type safe and pycharm complaints

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#131]
See screenshot for context: 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/7863287/215896614-5851d109-4c72-4752-b03e-0e27ce56583a.png">

It's not type safe coz it doesn't satisfy LSP - i.e. every derived class method should be able to accept arbitrary number of `**soqs: 'SoquetT'`. 

We can either choose to ignore type checking here by removing `SoquetT` from the base class definition so that mypy doesn't type check the arguments at all. Or we'd have to somehow change the design to make it satisfy LSP.

**Comment by mpharrigan** [comment]
mypy is now enabled and we ignore this mis-match
