### ISSUE TITLE
Design for implementing ControlledGate/ControlledOperation in the bloq's world?

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#134]
@mpharrigan Have you already thought about this problem? Specifically, suppose we have a `CompositeBloq` and we want to construct a controlled / multiplexed version of the corresponding composite bloq. How do we do it? Can we implement a pattern similar to Cirq where each Bloq would have a `controlled_by()` method which can be called to generate a controlled version of that bloq?

**Comment by mpharrigan** [comment]
Subsumed by all the other issues and PRs on `Controlled`
