### ISSUE TITLE
Make `And` a leaf bloq

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#1346]
Specific changes that are needed to do this part of #873 :

 - Any unit test that relies on the "sigma" return value of `call_graph` will change. This is brittle to begin with. Need to port to `QECGatesCost` 
 - Cirq simulation needs the cirq-style decomposition unless we override `_kraus_` with custom kraus operators. 
 - Shim over the `_t_complexity_` values for the time being.

**Comment by mpharrigan** [comment]
note: the `keep` argument can be removed from the unit tests in `permutation_test.py` after this is done

**Comment by mpharrigan** [comment]
There is now a flag called `FLAG_AND_AS_LEAF` which -- when set to True -- will turn `And` into a leaf bloq. There is a method called `to_clifford_t_circuit()` which returns a cirq circuit. 

I've kept the `decompose_from_registers` method to support cirq simulation, because it's not straightforward to override the `_kraus_` method

**Comment by fdmalone** [comment]
@mpharrigan can you remind me what the annoying chemistry things were?

**Comment by mpharrigan** [comment]
I don't think "annoying" is the right word; but many of the chemistry tests define a reference toffoli count, multiply it by 4, and assert that it matches deduced T counts. This is usually done via the `sigma` return value of `bloq.call_graph()`. Changing the status of `And` changes the contents of `sigma`. The tests need to be re-worked to compare the toffoli counts directly via new sigma values or porting to `QECGatesCost`.

**Comment by fdmalone** [comment]
@mpharrigan is there something else I can do here?

**Comment by anurudhp** [comment]
@fdmalone are you working on this? If not I have some wip code that i'd written for my other PR. I'm happy to polish that and make a PR

**Comment by fdmalone** [comment]
Go for it, I was mainly focused on cleaning up the tech debt of the
chemistry bloqs, let me know if you hit anything.

**Comment by mpharrigan** [comment]
I'm not sure what else needs doing. If tests pass after setting / removing the `FLAG_AND_AS_LEAF` then it's probably pretty close to being done-done
