### ISSUE TITLE
Classical simulation doesn't work for registers with non-empty shape and dtype != QUInt

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#1416]
The following sample code fails with an error: 

```python
import attrs
from qualtran import QInt, Bloq, Signature, Register

@attrs.frozen
class TestMultiDimensionalReg(Bloq):
    n: int

    @property
    def signature(self):
        return Signature([Register('x', QInt(32), shape=(self.n,))])


    def on_classical_vals(self, x):
        print(x)
        return {'x': x}

bloq = TestMultiDimensionalReg(10)
bloq.call_classically(x=[-1] * 10)
```

Issue is due to hardcoded casts to unsiged types `np.uint`s in https://github.com/quantumlib/Qualtran/blob/db8b9938d8210024bb6b92942376363586165efc/qualtran/simulation/classical_sim.py#L47-L56

**Comment by mpharrigan** [comment]
I suspect those casts harken back to the time when there weren't data types and the classical simulation only did unsigned integers. This is used to initialize a multidimensional numpy array to contain the values. The data type of this numpy array should probably delegate to the `QDType`
