### ISSUE TITLE
get_cost_value fails when applied to a CirqGateAsBloq with a known decomposition into gates that should be countable.

### ISSUE THREAD

**Issue by wjhuggins** [quantumlib/Qualtran#1426]
When I execute the code:
```
import sympy
import cirq

from qualtran.cirq_interop import CirqGateAsBloq
from qualtran.resource_counting import QECGatesCost, get_cost_value

theta = sympy.Symbol("theta", real=True)
cirq_swappow = cirq.SwapPowGate(exponent=theta)

# Would be cool if it worked:
swappow_bloq = CirqGateAsBloq(cirq_swappow)

get_cost_value(swappow_bloq, QECGatesCost())
```

I would expect that get_cost_value would automatically use cirq.decompose to break the SwapPowGate into gates that can be ingested by Qualtran and costed out, but instead I get an error message:

`ValueError: Cirq gate must be directly countable, not SWAP**theta`.

When I run (with the appropriate imports of course)
```
g, sigma = swappow_bloq.call_graph()

show_call_graph(g)

show_counts_sigma(sigma)
```

I get the expected behaviour:
<img width="385" alt="image" src="https://github.com/user-attachments/assets/5f347a21-3fa6-45bc-a8bf-5b63cec3ccfe">

**Comment by mpharrigan** [comment]
I was trying to limit the use of cirq functionality in the resource counting code but was overzealous here. I agree the call graph and resource counting code should be in agreement
