### ISSUE TITLE
0.5.0 backwards compatibility

### ISSUE THREAD

**Issue by rroodll** [quantumlib/Qualtran#1435]
I'm trying to update my application to use 0.5.0, but seem to be missing a number of methods. Most of which I found moved, but the following, can you point my to where they were moved and how they were replaced?
Thanks

qualtran.cirq_interop.bit_tools
qualtran.linalg.lcu_util.preprocess_lcu_coefficients_for_reversible_sampling

preprocess_lcu_coefficients_for_reversible_sampling is actually mentioned as a reference in a comment in 
![image](https://github.com/user-attachments/assets/6c926d05-aa55-42d1-81e5-5a4126a4865e)

**Comment by rroodll** [comment]
I was hoping you'd say that! Thanks.

were qualtran.cirq_interop.bit_tools removed?

**Comment by tanujkhattar** [comment]
Yes, but the bit tools functionality is now moved to the data types. So each quantum data type knows how to convert itself to / from bits. See the `QDType.to_bits` and `QDType.from_bits` methods

**Comment by rroodll** [comment]
Thanks
