### ISSUE TITLE
Can't render "<" or ">" in Bloq.pretty_name

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#221]
Hit this recently, not sure if it's a local issue or not. @mpharrigan have you seen this?

with

```python 
def pretty_name(self) -> str:
    return "a > b"
```

`
"dot" with args ['-Tsvg', '[/tmp/tmpu9o5sj1b]'] returned code: 1

stdout, stderr:
 b''
b"Error: [/tmp/tmpu9o5sj1b]: syntax error in line 11 near '>'\n"

Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?ffdbdf11-f794-4dd5-b1c8-b4eb319a1609)---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], line 4
      1 from cirq_qubitization.bloq_algos.arithmetic import GreaterThan
      3 bloq = GreaterThan(bitsize=4)
----> 4 show_bloq(bloq)

File [~/projects/cirq-qubitization/cirq_qubitization/jupyter_tools.py:62], in show_bloq(bloq)
     61 def show_bloq(bloq: Bloq):
---> 62     return PrettyGraphDrawer(bloq).get_svg()

File [~/projects/cirq-qubitization/cirq_qubitization/quantum_graph/graphviz.py:349), in GraphDrawer.get_svg(self)
    347 def get_svg(self) -> IPython.display.SVG:
    348     """Get an IPython SVG object displaying the graph."""
--> 349     return IPython.display.SVG(self.get_svg_bytes())

File [~/projects/cirq-qubitization/cirq_qubitization/quantum_graph/graphviz.py:345), in GraphDrawer.get_svg_bytes(self)
    343 def get_svg_bytes(self) -> bytes:
    344     """Get the SVG code (as bytes) for drawing the graph."""
--> 345     return self.get_graph().create_svg()

File [~/miniconda3/envs/qubitization/lib/python3.10/site-packages/pydot.py:1733), in Dot.__init__..new_method(f, prog, encoding)
   1729 def new_method(
   1730         f=frmt, prog=self.prog,
   1731         encoding=None):
...
   1961         )
   1962     )
   1964 return stdout_data

AssertionError: "dot" with args ['-Tsvg', '[/tmp/tmpu9o5sj1b]] returned code: 1
`

**Comment by fdmalone** [comment]
I think this is closed (math should be in short_name)

**Comment by mpharrigan** [comment]
Oh yeah I think I fixed this in https://github.com/quantumlib/Qualtran/pull/428
