### ISSUE TITLE
Can we make T-complexity protocol smarter for small 1/2q gates ?

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#233]
For example: `Controlled-H` can be implemented using 2 T gates. We can "derive" this information using existing knowledge in Cirq; for example: Cirq currently has decomposition of an H gate in terms of `Y ** 0.25, X, Y ** -0.25`

https://github.com/quantumlib/Cirq/blob/683286b9db96cc4a5fa405297de7090387e03ab0/cirq-core/cirq/ops/common_gates.py#L1006-L1008

We can use this information to figure out the fact that a `Controlled-H` gate can be implemented by controlling only the `X` gate and `Y ** 0.25` is equivalent to a `T` gate upto a clifford rotation. 

Another general approach would be to implement a general synthesizer to decompose arbitrary 1/2q in terms of T gates (eg: https://github.com/quantumlib/Cirq/issues/5815)

**Comment by fdmalone** [comment]
possible connected to #237 which costs a Toffoli

**Comment by mpharrigan** [comment]
The strategy going forward here is to 

 - keep the bloqs in the call graph as leafs if there's flexibility in how they would be implemented depending on architecture #873 
 - everything should be bloqs and these sorts of final tricks can be factored into e.g. `t_complexity_protocol._from_directly_countable`. 

closing this issue. For specific gates that need more intelligent t counts, feel free to open specific issues
