### ISSUE TITLE
Make comparison gates use 4 * N T-gates to compare and 0 T-gates to uncompute using MBUC

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#235]
We can use Craig's out of place adder to compute using 4 * N T-gates and uncompute using 0 T-gates as described in https://arxiv.org/pdf/1709.06648.pdf.

**Comment by mpharrigan** [comment]
Is this done?

**Comment by NoureldinYosri** [comment]
not completly, some comparison gates use 4T others use 8T. I will send a couple of PR to address this

**Comment by mpharrigan** [comment]
Is this done now?

**Comment by NoureldinYosri** [comment]
not all of them .. some comparison bloqs use the n log n decomposition

**Comment by NoureldinYosri** [comment]
now there are versions for the linear depth 4T comparators ... there are also some comparators that use log depth (8T)  constructors ... so both options are supported
