### ISSUE TITLE
Multi-Control Pauli Decomposition is probably incorrect

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#240]
Right now, we don't have a test for correctness and as part of writing a gate locally,  I discovered that the gate is probably not doing what it's promised to do (I tested for `cirq.Z(q).controlled_by(*control_qubits, control_vals = [0] * len(control_qubits))`) 

This issue is to verify the correctness and add a validation test:

https://github.com/quantumlib/cirq-qubitization/blob/a2f283e0269d92d89aba2ce19e5b973019db5aca/cirq_qubitization/cirq_algos/multi_control_multi_target_pauli.py#L44

**Comment by fdmalone** [comment]
@tanujkhattar I hit this recently and remembered I was supposed to look into it. Any idea what's going on before I dig in?

**Comment by mpharrigan** [comment]
@tanujkhattar did you fix this?

**Comment by anurudhp** [comment]
#790 added tensor tests to verify the action, closing.
