### ISSUE TITLE
Write multi dimensional versions of common 2 qubit operations in Cirq to act on qubit registers. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#27]
Add support for common 2-qubit operations in Cirq to act on qubit registers instead of qubits. For example:
* Swap 
* Multi target single controlled SWAP
* CNOT 

Provide efficient decompositions under the hood in terms of optimizing T gates.

**Comment by mpharrigan** [comment]
We have

 - `TwoBit[C]Swap` and `[C]Swap`
 - `And` and `MultiAnd`
 - `MultiTargetCNOT`
 - `MultiControlPauli`

Any others?

**Comment by mpharrigan** [comment]
Closing in favor of more specific follow-on issues/requests
