### ISSUE TITLE
Enable and fix mypy

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#303]
We largely have type annotations throughout the code and I always keep an eye on the pycharm type-checker. However, we should enable mypy as part of the continuous integration (CI) checks. There are currently a lot of mypy warnings.

**Comment by fdmalone** [comment]
bloq_counts mypy errors too: See for example and_bloq.py: Return type "Set[Tuple[int, Bloq]]" of "bloq_counts" incompatible with return type "Set[Tuple[Union[int, Expr], Bloq]]" in supertype "Bloq"  [override]

**Comment by mpharrigan** [comment]
why isn't that allowed? I thought overrides were allowed to have more specific types

**Comment by dstrain115** [comment]
mypy is now enabled as of #926
