### ISSUE TITLE
Add tools for doing accurate resource estimation on circuits

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#32]
We have recently added a bunch of primitives for simulating chemistry Hamiltonian's. However, the ultimate goal is to be able to do resource estimation on circuits constructed using these primitives. Write an analogue of `QCTraceSimulator` in Q# that can consume Cirq circuits and do resource estimation on those circuits. 

Some Potential design considerations for accurate resource estimation by compiling the constructed circuits:
* `cirq.estimate_resources(circuit, config = esimation_config, gateset = target_gateset)` where `target_gateset` can be `T + Cliffords + Measurement`, `Toffoli + Cliffords + Measurement` etc.  
* Implement (hardcoded + analytical) decompositions of known (and unknown) gates into the target gatesets supported above by resource estimation. 
* Provide support for different resource estimation configurations (for example: control tradeoff between optimizing for depth vs qubit count). 
* Find a way of replacing different implementations of a primitive (eg: AND / Swap / etc.) that have different decompositions optimized for T-count / circuit depth / qubit count etc.

**Comment by mpharrigan** [comment]
closing in favor of #539  #735 and other more-specific issues
