### ISSUE TITLE
Add constructor option to specify a model for a Gate.

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Qualtran#326]
Since we are creating our own basic gates.. I think we should add an option to their constructor to specify some information about their decomposition.

For examples:

Toffoli:
  - optimal T complexity without ancilla is  7. this means that doing and undoing Toffoli costs 14T
  - using ancilla it has T complexity of 4. this means that doing and undoing Toffoli costs only 4T

CSWAP:
  - optimal T complexity without ancilla is  7. this means that doing and undoing CSWAP costs 14T  https://github.com/quantumlib/Cirq/blob/master/cirq-ft/cirq_ft/infra/decompose_protocol.py#L24
  -  optimal T complexity without ancilla but with a phase error of -1 is 4. this means that doing and undoing CSWAP costs 8T.  https://github.com/quantumlib/Cirq/blob/master/cirq-ft/cirq_ft/algos/swap_network.py#L71
  - using ancilla it has T complexity of 4. this means that doing and undoing CSWAP costs only 4T. https://github.com/quantumlib/Cirq/blob/master/cirq-ft/cirq_ft/algos/arithmetic_gates.py#L166

To accomadate these variations we now have multiple decompositions of CSWAP floating in Cirq and Cirq-FT.

We should be able to do something like 

```py3
qualtran.basic_gates.CSWAP(model = 'arxiv:123')
qualtran.basic_gates.Toffoli(model=custom_decompose_func)
```

This is also related to https://github.com/quantumlib/Qualtran/issues/110

**Comment by mpharrigan** [comment]
The plan here is to make T, Toffoli, and CSWAP leaf bloqs #873 

There are arguments to `GateCounts.total_t_counts()` where you can pick your favorite constants
