### ISSUE TITLE
Getting started guide for Qualtran?

### ISSUE THREAD

**Issue by christopherkang** [quantumlib/Qualtran#334]
Is there a "getting started" guide for qualtran / list of docs to look at? I'm guessing that the "/docs" branch has the up-to-date docs, but I'm not sure where to start. Would love more guidance on what to read to make use of the tool.

**Comment by mpharrigan** [comment]
The docs are available at https://qualtran.readthedocs.io/ and you can find a tutorial there. Please don't hesitate to send feedback
