### ISSUE TITLE
Question about Hadamard gate

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#342]
Currently the hadamard gate is sort of implemented as Plus/Minus State/Effect. Do we want the gate by itself too? For multi qubit Hadamards should I use _XVector(...,n=num_qubits)? @mpharrigan

**Comment by mpharrigan** [comment]
yes, we want the gate too

**Comment by mpharrigan** [comment]
I'll do this; I had started it xref #323 #321 #322

**Comment by fdmalone** [comment]
oh whoops

**Comment by mpharrigan** [comment]
you mean #343 :p

**Comment by fdmalone** [comment]
yikes
