### ISSUE TITLE
Bloq counts graph fails to merge edges correctly when using `generalizer`

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#367]
From the notebook combining Ands:
![Screenshot 2023-09-25 at 2 04 56 PM](https://github.com/quantumlib/Qualtran/assets/12097876/adeb370f-e6b2-4535-90ee-5edbb14d4c45)
yields:
![Screenshot 2023-09-25 at 2 04 11 PM](https://github.com/quantumlib/Qualtran/assets/12097876/b3b6c385-59de-4ba3-9e5f-f6a7cbef765a)

The first graph looks fine T count = (2x4 + 3x4) = 20, but the second merged example looks like 5x8 = 40.

**Comment by fdmalone** [comment]
The actual final T count is the same either way, but I was a bit confused as to what was going on.

**Comment by fdmalone** [comment]
cc @mpharrigan

**Comment by mpharrigan** [comment]
oh weird. Let me investigate

**Comment by mpharrigan** [comment]
Right: so we want the "2" and "3" arrows to _add_ when the `And`s are combined but we want the "4" arrows to .. idk either take the max or assert that they are equal. 

Right now, the code does a DFS (and adds everything correctly to return the total counts `sigma`) so it will descend into `And` twice. I think switching to a BFS might fix the issue, but I have to think about it some more.

**Comment by fdmalone** [comment]
I think assert equality makes most sense right? We probably shouldn't be generalizing bloqs that are different.

**Comment by mpharrigan** [comment]
You can trigger this bug without using `generalizer` at all if you have a "funnel" topology where two paths merge into one path. The outgoing arrow from the end of the funnel will have an extra multiplicative factor according to the number of incident paths. A dag is not a tree!
