### ISSUE TITLE
Alternative rotation compilations/costs

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#370]
Currently our T costs derive from  https://arxiv.org/pdf/1404.5320.pdf, which gives a mean cost of 1.149 log2
(1/ε) + 9.2 for a target precision of ε.

Many papers use a phase gradient gate instead for rotations (appendix A of https://doi.org/10.1103/PRXQuantum.1.020312) which requires b_r - 2 Toffolis for b_r bits of precision (it uses the first method to prepare a phase gradient register first and then adds into this). This is often significantly cheaper.

Need to think about rotations.

**Comment by mpharrigan** [comment]
cc @NoureldinYosri who has been thinking about this

**Comment by NoureldinYosri** [comment]
we currenly have a unified approach to the vanilla rotation models [RotationLogarithmicModel](https://github.com/quantumlib/Qualtran/blob/57de77ef6fd2172330e99e121f603045197fd884/qualtran/surface_code/rotation_cost_model.py#L37) and for constant cost models [ConstantWithOverheadRotationCost](https://github.com/quantumlib/Qualtran/blob/57de77ef6fd2172330e99e121f603045197fd884/qualtran/surface_code/rotation_cost_model.py#L69C7-L69C39) both of which implement the same interface of [RotationCostModel](https://github.com/quantumlib/Qualtran/blob/57de77ef6fd2172330e99e121f603045197fd884/qualtran/surface_code/rotation_cost_model.py#L24)

Do we need to do more for this?

**Comment by mpharrigan** [comment]
Related: #1250

**Comment by mpharrigan** [comment]
Going to close this in favor of #1250 or open new issues to track specific asks
