### ISSUE TITLE
Add openfermion dependency?

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#395]
It can be convenient for testing to compare to openfermion's existing cost estimates. yay/nay on adding it as a dependency?

**Comment by mpharrigan** [comment]
We have a notion of test dependencies vs runtime dependencies. If it's just used for tests then go 4 it

**Comment by mpharrigan** [comment]
If adding it only as a test dependency or doc-dependency is sufficient, I'm going to close this issue and you can open your PR at your leisure.

If you need to take a runtime dependency on openfermion, let's discuss what is specifically needed.
