### ISSUE TITLE
Bloq count graphs can be quite wide

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#400]
see trotter.ipynb #359  and #392, should they be more vertical?

**Comment by mpharrigan** [comment]
What about making the node labels more configurable? and/or changing the default to be more sensitive to long reprs

**Comment by mpharrigan** [comment]
In terms of making them "more vertical": currently I think it tries to have each level correspond to a topological generation. We use graphviz under-the-hood so be on the lookout for layout options there

**Comment by mpharrigan** [comment]
With the new call graphs with costs, they're at least a bit more vertical; and the `__str__` reprs are much shorter so they won't be as wide. Closing for now unless there are feasible suggestions on how to improve the layout further.
