### ISSUE TITLE
`CompositeBloq` cannot store isolated Bloqs, like a `GlobalPhaseBloq`.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#422]
`CompositeBloq` represents a graph using a list of edges stored as `connections`. This has a fundamental limitation that we cannot store isolated nodes in the graph, for example a `GlobalPhaseBloq` (equivalent to a cirq.GlobalPhaseGate). 

It is often important to store Global phase as part of the compute graph and I think we need a way to get around this limitation. Some possible options are as follows:

1. One way would be to store both nodes (as `FrozenSet[BloqInstance]`) and connections (the way we do now, `Tuple[Connection, ...]`) 
2. A hacky solution would be to store a self loop (i.e. a connection with both the end points on the same node) to represent an isolated node. 

I think way-1 is strictly better and we should do that. cc @mpharrigan

**Comment by mpharrigan** [comment]
What's the use case for storing global phase? That should be an emergent property from the bloqs.

**Comment by tanujkhattar** [comment]
Applying a `CompositeBloq.controlled()` will turn global phase into local phase and give you wrong results the global phase of your composite bloq is not correct.
