### ISSUE TITLE
`ccz2t_cost_model` fails opaquely when the error budget is too low

### ISSUE THREAD

**Issue by StefanoPolla** [quantumlib/Qualtran#535]
The function get_ccz2t_costs fails when the total error budget is lower than the distillation error. However, the exception raised is not informative. 
This possible failure should be considered a common occurrence when calling this function. It could be handled with a separate check and documented.

e.g. using default CCZ2T factory and error budget, and algorithm parameters from [arXiv:2011.03494](https://arxiv.org/abs/2011.03494)

```
from qualtran.surface_code.ccz2t_cost_model import get_ccz2t_costs, AlgorithmSummary

get_ccz2t_costs(n_magic = AlgorithmSummary(toffoli_gates = 3.2E10),
                n_algo_qubits = 2196)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 3
      1 from qualtran.surface_code.ccz2t_cost_model import get_ccz2t_costs, AlgorithmSummary
----> 3 get_ccz2t_costs(n_magic = AlgorithmSummary(toffoli_gates = 3.2E10),
      4                 n_algo_qubits = 2196)

File ~/git_repositories/packages/Qualtran/qualtran/surface_code/ccz2t_cost_model.py:204, in get_ccz2t_costs(n_magic, n_algo_qubits, phys_err, error_budget, cycle_time_us, routing_overhead, factory, data_block)
    202     data_unit_cells = n_logical_qubits * n_cycles
    203     target_err_per_round = err_budget / data_unit_cells
--> 204     data_d = code_distance_from_budget(phys_err=phys_err, budget=target_err_per_round)
    205     data_block = SimpleDataBlock(data_d=data_d, routing_overhead=routing_overhead)
    207 data_error = data_block.data_error(
    208     n_algo_qubits=n_algo_qubits, n_cycles=n_cycles, phys_err=phys_err
    209 )

File ~/git_repositories/packages/Qualtran/qualtran/surface_code/formulae.py:46, in code_distance_from_budget(phys_err, budget)
     42 """Get the code distance that keeps one below the logical error `budget`."""
     44 # See: `error_at()`. p_l = a Λ^(-r) where r = (d+1)/2
     45 # Which we invert: r = ln(p_l/a) / ln(1/Λ)
---> 46 r = math.log(10 * budget) / math.log(100 * phys_err)
     47 d = 2 * math.ceil(r) - 1
     48 if d < 3:

ValueError: math domain error
```

**Comment by fdmalone** [comment]
an abs() around error_budget - distillation_error would "solve" the problem but not sure if there is something else going on.

**Comment by StefanoPolla** [comment]
If error_budget < distillation_error, there's no way of obtaining a total error below budget.

What would be the desired behaviour in that case? I imagine raising a custom "ErrorAboveBudget" exception or returning a fail state. What's the best practice?

Note that handling this exception in an outer loop would be key in implementing something alike to [`openfermion.cost_estimator`](https://github.com/quantumlib/OpenFermion/blob/0c3c528798147d3c6eaf8602fd100e55b0799526/src/openfermion/resource_estimates/surface_code_compilation/physical_costing.py#L171)

**Comment by fdmalone** [comment]
right so you want to catch this case when scanning over some parameters, it's not necessarily a bug in the code (beyond the catching of the exception)? Does openfermion also fail in this case?

cc @mpharrigan / @NoureldinYosri who are working on these things, but raising a ValueError would work. This should be added as a unit test too?

Now that openfermion is also a test dependency it may be worth doing one-to-one comparison tests too if appropriate.
