### ISSUE TITLE
Reproducing physical costings from literaure with CCZ2T factories

### ISSUE THREAD

**Issue by StefanoPolla** [quantumlib/Qualtran#553]
I am trying to reproduce physical costings from literature, e.g. (THC)[https://arxiv.org/abs/2011.03494].

To do this, there are two features that I'm missing in the physical_costing module:
1. the possibility of using multiple magic state factories. In the THC paper, 4 CCZ2T factories are used.
2. an optimization over the factory parameters (code distance in level 1 and 2 distillation), similar to what is done in (`openfermion.resource_estimates.surface_code_compilation.physical_costing.cost_estimator`)[https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/resource_estimates/surface_code_compilation/physical_costing.py#L171] through the `iter_known_factories` generator.

This issue connects to issue #535 and PR #475, as an extension of `qualtran.surface_code.ccz2T_cost_model`

**Comment by StefanoPolla** [comment]
I have written some code to solve this, I can try to fork and integrate this code. Let me know if I should go on with this.

To solve 1, I wrote an overlay class `MultiCCZ2TFactories(CCZ2TFactory)`, which naively multiplies the footprint and divides the n_cycles by the number of factories used. I could generalize it an overlay of any MagicStateFactory.

**Comment by fdmalone** [comment]
cc @NoureldinYosri who has been developing these things.

**Comment by mpharrigan** [comment]
Ideally it would be `MultiFactory` that works with any sub-factory

**Comment by mpharrigan** [comment]
This is done
