### ISSUE TITLE
Bloq counts / t_complexity for QRO(A)M is pretty slow

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#559]
[add evidence]

**Comment by tanujkhattar** [comment]
The `cirq_ft.t_complexity` protocol was optimized for performance due to aggressive caching. In Qualtran, we've not paid attention to performance so far. We should add caching to the `bloq.t_complexity()` method to speed things up similar to Cirq-FT

**Comment by fdmalone** [comment]
@mpharrigan just FYI, my not very scientific profile for qrom:

``` python
import time

import numpy as np

from qualtran.bloqs.qrom import QROM

for dim in np.linspace(10, 100, 5, dtype=int):
    data = np.random.randint(0, 100, size=(dim, dim))
    start = time.time()
    qrom = QROM.build([data] * 4)
    time_build = time.time() - start
    start = time.time()
    t_comp = qrom.t_complexity()
    time_t_compl = time.time() - start
    start = time.time()
    graph, sigma = qrom.call_graph()
    time_call_graph = time.time() - start
    print(
        f"{dim} time build = {time_build}, t_compl = {time_t_compl}, call_graph = {time_call_graph}"
    )

```
10 time build = 5.8650970458984375e-05, t_compl = 0.0577545166015625, call_graph = 0.6501712799072266
32 time build = 0.00010061264038085938, t_compl = 0.7631957530975342, call_graph = 6.089676380157471
55 time build = 0.00012874603271484375, t_compl = 2.1280786991119385, call_graph = 16.60946536064148
77 time build = 0.0001499652862548828, t_compl = 4.321039438247681, call_graph = 34.739116191864014
100 time build = 0.00022411346435546875, t_compl = 6.794877529144287, call_graph = 57.8678514957428

Note for chemistry algorithms we may want to cost things out which have data sets with N^4-> N^2 amount of data where N ~ 100-1000, so we probably don't want to construct the circuits explicitly anyway and should work out the correct formula for T (known) and clifford (can be worked out) count

**Comment by mpharrigan** [comment]
thanks for the timing. The leading theory is that the majority of the time comes from `QROM.decompose_bloq()`, yes?

**Comment by fdmalone** [comment]
yes

**Comment by tanujkhattar** [comment]
I think there's also an issue here that needs to be addressed separately - the qualtran style decomposition is ~5x slower than cirq style decomposition. 

```python
import time

import numpy as np

from qualtran.bloqs.qrom import QROM
from qualtran.cirq_interop.testing import GateHelper
import cirq

for dim in np.linspace(1000, 10_000, 5, dtype=int):
    data = np.random.randint(0, 100, size=dim)
    start = time.time()
    qrom = QROM.build(data)
    time_build = time.time() - start
    start = time.time()
    cbloq = qrom.decompose_bloq()
    time_qualtran_decompose = time.time() - start
    start = time.time()
    circuit = cirq.Circuit(cirq.decompose_once(GateHelper(qrom).operation))
    time_cirq_decompose = time.time() - start
    print(
        f"{dim} time build = {time_build}, qualtran_decompose = {time_qualtran_decompose}, "\
        f"cirq_decompose = {time_cirq_decompose}, slow_by = {int(time_qualtran_decompose/time_cirq_decompose)}x"
    )
```

gives the output
```
1000 time build = 0.0004439353942871094, qualtran_decompose = 1.3346881866455078, cirq_decompose = 0.21526074409484863, slow_by = 6x
3250 time build = 6.103515625e-05, qualtran_decompose = 4.662091970443726, cirq_decompose = 0.9593257904052734, slow_by = 4x
5500 time build = 7.295608520507812e-05, qualtran_decompose = 8.541254758834839, cirq_decompose = 1.0852549076080322, slow_by = 7x
7750 time build = 0.00011992454528808594, qualtran_decompose = 11.836782932281494, cirq_decompose = 2.699848175048828, slow_by = 4x
10000 time build = 7.200241088867188e-05, qualtran_decompose = 15.199790000915527, cirq_decompose = 3.4773008823394775, slow_by = 4x

```


In general, I think `decompose_bloq` is should be made more performant (all protocols, like costs / call graph / serialization will benefit from this). I remember we had discussed this during the initial prototyping phase but it wasn't considered to be a blocker at that point. I think now we should start paying more attention to it and consider ways to speed up the `decompose_bloq` method.

**Comment by mpharrigan** [comment]
iirc the last time I profiled it, a lot of time was consumed by pushing and popping soquets out of and into the `available` set to make sure they're used once and and only once. You could probably just eliminate this check or do a more performant version of it only during `bb.finalize()`.

I guess I'm trying to say: profile first!
