### ISSUE TITLE
Refactor `classical_sim.py` bitwise functions to allow for signed values

### ISSUE THREAD

**Issue by fpapa250** [quantumlib/Qualtran#606]
`bits_to_ints()` and `ints_to_bits()` only work for conversions of unsigned integers. This limits the classical simulation correctness for bloqs using `Join()` because its `on_classical_vals()` implementation uses these functions. Therefore when we get the classical simulation of a bloq that uses `Join()` it cannot represent signed integers so we can't have tests for classical simulation of signed integer representations.

Currently this affects the signed implementation of `Add()` and doesn't allow us to classically simulate `SimpleAddConstant()`. Once this functionality has been changed we need to add tests for the classical simulation of the signed version of `SimpleAddConstant()`.

**Comment by fdmalone** [comment]
in general I think we want a type_to_bits and bits_to_type method which will appropriately dispatch based on the type of the register. For fixed point we can probably write a little python implementation to define operations given some limited precision.

**Comment by fpapa250** [comment]
For tracking purposes: Also an issue for comparison of negative integers in the `GreaterThan()` bloq.
