### ISSUE TITLE
[data types] Better names for data types

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#632]
We should probably make the changes:

1. QUnsignedInt -> QUInt
2. QFixedPoint -> QFxP
3. BoundedQInt -> BoundedQUInt (we're never using the signed variation)

I think we should just add types as necessary rather than trying to be exhaustive (QUFxP for example). For 3 I will make the change in the selection register deprecation.

**Comment by mpharrigan** [comment]
QFxP is pushing it lol

**Comment by fdmalone** [comment]
Glass houses

**Comment by tanujkhattar** [comment]
`QFxP` is motivated from similar terminology in https://github.com/francof2a/fxpmath, which we'll probably end up using extensively. See https://github.com/quantumlib/Qualtran/pull/635 for a first usage.

**Comment by fdmalone** [comment]
I'm fine with either, I sort of prefer the capitalization for separate words, but if we eventually adopt their spec then it's most natural.
