### ISSUE TITLE
Support data types in classical simulation

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#643]
Add dtype specific validation to the various steps. Maybe beef up the test fixtures as well. cc @fdmalone

**Comment by fdmalone** [comment]
From #651 we need updates for:

1. QFxp
2. BoundedQInt
3. QIntOnesComplement

**Comment by mpharrigan** [comment]
Is this done?

**Comment by fdmalone** [comment]
No, I need to profile to see why Fxp is so slow.
