### ISSUE TITLE
GateWithRegisters supports_decompose_bloq returns false when a Cirq decomposition is specified

### ISSUE THREAD

**Issue by skushnir123** [quantumlib/Qualtran#670]
I came across this issue when calling supports_decompose_bloq on an instance of a PhaseGradientUnitary Bloq and it returned false even though a decomposition is specified. It seems this is a more general issue with bloqs which specify a Cirq decomposition.

**Comment by mpharrigan** [comment]
Yes, this is likely a bug.

Can I ask why you're using that method? In general: it's probably more trouble than it's worth, and we could consider directing users to just try decomposing and see if an exception is raised.
