### ISSUE TITLE
Pulling from PYPI still resolves as 0.1.0

### ISSUE THREAD

**Issue by rroodll** [quantumlib/Qualtran#692]
I've tried pulling the latest from pypi, even doing the normal

pip install qualtran

ends up pulling version 0.1.0 instead of 0.2.0

I'm not sure if this is simply a labeling problem on pypi or it is actually giving us the incorrect version.
I tried pulling the github code down as well and even though the version in _version.py = 
![image](https://github.com/quantumlib/Qualtran/assets/139884082/9031e90d-a367-4367-b978-3e9ce3eb8cf1)

it pip installs locally as 0.1.0

**Comment by mpharrigan** [comment]
the latest on pypi is indeed 0.2.0

https://pypi.org/project/qualtran/

Have you tried either

```
pip install -U qualtran
```

or 

```
pip install qualtran==0.2.0
```

**Comment by rroodll** [comment]
after some more testing and research, this appears to be a 10 year old known bug in pip. Apparently it has something to do with the pip installer taking a local cached version.

passing in the current version from pypi does indeed work. I had hoped to have our installer just take the latest, but it appears that may not always work.

OS thread:
https://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package

**Comment by rroodll** [comment]
just for brevity and in case anyone else trips across this...

the true issue was unmasked when I changed our install to tie it to qualtran==0.2.0

that uncovered that the qualtran==0.2.0 was requiring cirq-core's October build, but we were requiring the Nov build. A simple wind-back to match the versions fixed the problem.

![image](https://github.com/quantumlib/Qualtran/assets/139884082/039b9f96-02d1-40bf-86ab-5e9fd4700557)

**Comment by mpharrigan** [comment]
sorry about that. I think after cirq 1.4 is released we won't be tied to a particular cirq version @tanujkhattar

**Comment by mpharrigan** [comment]
The reason why we bumped the pin was to pull in this bugfix pr

https://github.com/quantumlib/Cirq/pull/6467

to fix this issue

https://github.com/quantumlib/Qualtran/issues/665

I think this PR introduced the problem: https://github.com/quantumlib/Cirq/pull/6332

but I just installed cirq-core==1.3 and ran the qualtran tests against `main` and there weren't any errors, so maybe we can change the requirement to `cirq-core>=1.3` @tanujkhattar  what do you think

**Comment by tanujkhattar** [comment]
I think it's been a quarter since we did a Cirq release so we can go ahead and do that as well. Otherwise we can definitely do a patch release to get these changes in instead of depending on an older version of Cirq. cc @pavoljuhas

**Comment by pavoljuhas** [comment]
@tanujkhattar - let us sync on Monday about what is the best option to do.  (I am OOO today)
