### ISSUE TITLE
Better musical score and graph drawing control for registers via `wire_symbol`

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#728]
- change the `wire_symbol` method to explicitly take a `Register` and `idx: Tuple[int, ...]` rather than one `Soquet` since the symbol shouldn't depend on the `binst`.
 - Eliminate or rename or merge `short_name` to explicitly compliment the wire symbols. This string should serve (solely) as a "title" to be written above the wire symbols and should be included if and only if the wire symbols don't already imply the gate. E.g. it's not necessary to write "CNOT" over something that's clearly a CNOT. Practically: we can rename the existing method and let it return `None` _or_ we can use a sentinel value to the `wire_symbol` method (e.g. `reg=None`) to imply that we're asking for the (optional) title.
 - Single source of truth for drawing: modify the `GraphvizDrawer` for drawing composite bloq graphs to use the `wire_symbol` method and values to label the soquet rows in the table for each bloq. Use the title method for the title, and again omit if not required. Practically: we'll need a new method on `WireSymbol` to return a textual equivalent of the symbol

**Comment by mpharrigan** [comment]
For the third point, since we don't actually draw the symbols in the graphviz drawer: I propose instead to follow #791 where we should have meaningful, concise `__str__` methods on all the bloqs and use that

**Comment by mpharrigan** [comment]
Ok, I just actually read the issue that I linked (and wrote) and it seems in all these places I seemed pretty convinced that the diagrams should use the wire_symbols for composite bloq diagrams (graphviz and musical_score). Let's try that. We can move the graphviz drawer to use `str()` later if it's too ambiguous otherwise

**Comment by dstrain115** [comment]
This has been completed.  See above PRs for details.
