### ISSUE TITLE
Some Bloqs will not serialize.

### ISSUE THREAD

**Issue by Epsilon1024** [quantumlib/Qualtran#729]
This issue was originally discovered by serializing a composite bloq which contains an AND bloq.  The AND bloq fails to serialize and raises this [error](https://github.com/quantumlib/Qualtran/blob/090941f8d5697ce49cbf306056fa354690f95a03/qualtran/cirq_interop/_cirq_to_bloq.py#L312).  It is likely that there are other bloqs which will have similar problems.

A summary of the path to the error is as follows:

The path to the error is as follows:
1) Attempts to decompose bloq using bloq.decompose_bloq()
2) AND does not have this method implemented causing the decomposition to fallback on decompose_from_cirq_style_method().
3) This leads to it iterating through each of the individual [operations](https://github.com/quantumlib/Qualtran/blob/090941f8d5697ce49cbf306056fa354690f95a03/qualtran/cirq_interop/_cirq_to_bloq.py#L394).

4) One of these operations is both classically controlled and is not a gate which causes _extract_bloq_from_op to raise the error.

**Comment by Epsilon1024** [comment]
Please assign me to this issue as I am currently working on a fix.

**Comment by tanujkhattar** [comment]
The serialization code now tries to build a composite bloq; and if a composite bloq doesn't exist / cannot be built (eg: due to classically controlled operations appearing in the decomposition) it gracefully considers the bloq to be a leaf bloq. This issue can now be closed. 

```python
In [8]: bloqs_from_proto(bloqs_to_proto(And()))
Out[8]:
[And(cv1=1, cv2=1, uncompute=0),
 Allocate(dtype=QAny(bitsize=1)),
 Hadamard(),
 TGate(is_adjoint=0),
 CNOT(),
 TGate(is_adjoint=1),
 SGate(is_adjoint=0),
 ArbitraryClifford(n=2)]

In [10]: bloqs_from_proto(bloqs_to_proto(And().adjoint()))
Out[10]: [And(cv1=1, cv2=1, uncompute=1), ArbitraryClifford(n=2)]
```
