### ISSUE TITLE
Gateset Decomposition by level

### ISSUE THREAD

**Issue by rroodll** [quantumlib/Qualtran#759]
It would be nice to have the ability to specify different decomposition or different decomposition 'levels' (ie, we want to keep toffolis, or want to keep rotations, or want to keep something else).
 
We could imagine specifying a target gateset to decompose , which we can imagine being done by either by having multiple different decomposition methods, or via flags that are passed

Is this something that is already on the roadmap or could be added?

**Comment by mpharrigan** [comment]
`Bloq.flatten()` is closest to what you want. It takes a `max_depth` argument as well as a `pred` (predicate) argument. The predicate takes a bloq instance and returns True if it should be decomposed and flattened or False if it should be left alone
