### ISSUE TITLE
Determine operator 'level' by bloq

### ISSUE THREAD

**Issue by rroodll** [quantumlib/Qualtran#760]
It would be nice to understand how many 'operator levels' exist in a bloq. Ie, if we have an operator that decomposes into 1Q/2Q/CCX qubit gates, that would be level '0' (call it operatorA). If we have an operatorB that is composed of operatorA, then operatorB is at level '1'. And so on.
 
Being able to know the levels of an operator by itself is useful, and the 'global' levels of a circuit or composition is also useful. Is this something that exists or is on the roadmap?

**Comment by mpharrigan** [comment]
You can use `graph, _ = bloq.call_graph()` to look what builds on what. It's a networkx graph so you can assign a distance from the leaf nodes (level 0)
