### ISSUE TITLE
Update lcu_util to allow user to specify sub_bit_precision

### ISSUE THREAD

**Issue by kjm538** [quantumlib/Qualtran#799]
Can preprocess_lcu_coefficients_for_reversible_sampling be updated to allow the user to input epsilon or sub_bit_precision? Sometimes it is preferable to specify the number of precision bits explicitly.

**Comment by fdmalone** [comment]
I don't see why not. In the notebooks I believe we often set epsilon to be $2^{-n_b}$ directly, but it might be a bit more convenient to make this an optional input too.

**Comment by tanujkhattar** [comment]
@Vicara12 Can you take a look?
