### ISSUE TITLE
Consolidate bit iteration

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#811]
Currently we have https://github.com/quantumlib/Qualtran/blob/main/qualtran/cirq_interop/bit_tools.py and https://github.com/quantumlib/Qualtran/blob/main/qualtran/simulation/classical_sim.py which somewhat replicate functionality. These should be consolidated and possibly updated to support > 64 bit uints?

**Comment by mpharrigan** [comment]
Following #1041, classical_sim bit tools still needs to be ported
