### ISSUE TITLE
Add an OnEveryBit Bloq?

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#814]
We have OnEach which hides the splits / joins necessary to apply n single qubit gates to an n-qubit register. We could also add an OnEveryBit bloq to add a collection of single qubit gates (or maybe n-qubit gates in a more general form) to a bigger register. An example is applying a sequence of rotations which each have a different angle, which currently requires a split/join in the decomposition.

**Comment by fdmalone** [comment]
Hmm, maybe we just want something for rotations specifically, as I admit it's a bit specific, but it could also be helpful for say a tower of CNOTs.

**Comment by mpharrigan** [comment]
One approach would be to implement these cases "manually" and make a note or keep a list of the places where they crop up as empirical evidence of what sort of abstractions would see widespread use

**Comment by fdmalone** [comment]
Not important.
