### ISSUE TITLE
Greedy vs Simple Qubit Ancilla Manager decompose bug with prepareuniformsuperposition

### ISSUE THREAD

**Issue by akurlej** [quantumlib/Qualtran#818]
Greedy qubit manager fails with a duplicate QID on a CNOT in the ```LessThanConstant``` , SimpleQubitManager works without issue. 

Issue occurs with current release of qualtran (0.2.0)

Code to reproduce:
```
import cirq
from qualtran.bloqs.prepare_uniform_superposition import PrepareUniformSuperposition

n=3
target = cirq.NamedQubit.range((n-1).bit_length(),prefix='target')
control = [cirq.NamedQubit('control')]
circuit_error = cirq.inverse(cirq.Circuit(PrepareUniformSuperposition(n,cvs=(0,)).on_registers(ctrl=control,target=target)))

#Greedy fails, simple works
gqm = cirq.GreedyQubitManager(prefix="_ancilla", maximize_reuse=True)
#gqm = cirq.SimpleQubitManager(prefix="_ancilla")
cirq.decompose(circuit_error,context = cirq.DecompositionContext(gqm))
```

**Comment by rroodll** [comment]
@mpharrigan is there any update on this one? Thanks
btw - sent an email to your outlook addr when you get a chance

**Comment by tanujkhattar** [comment]
@akurlej @rroodll This is now fixed. Please let us know if you still run into any issues. Thanks for reporting and apologies it took so long to fix!

**Comment by rroodll** [comment]
Thanks @tanujkhattar! This is great. One of us will pull the latest and give it a test.
