### ISSUE TITLE
No explicit tests for `PRGAViaPhaseGradient`

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/Qualtran#840]
The documentation and testing is very light for this bloq.  Can this be expanded? it would seem it only has system testing via state-prep via rotations.

Reference:

https://github.com/quantumlib/Qualtran/blob/main/qualtran/bloqs/state_preparation/state_preparation_via_rotation_test.py

contains no tests for the mentioned bloq.

**Comment by ncrubin** [comment]
@Vicara12

**Comment by Vicara12** [comment]
@ncrubin I added a test on PR #846, which contains both an example of usage and also the formula for converting the desired angle into the value to be loaded in the QROM (which is what the bloq receives). Let me know if you have further feedback!
