### ISSUE TITLE
Appropriate way to add on/off single controlled bloq?

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#883]
Is there a simpler way to add a singly-controlled bloq:

``` python 
ctrl_spec = CtrlSpec(cvs=[0])
(ctrl,), q = bb.add(ZGate(), ctrl=(ctrl,), q=q)
```
seems a little awkward.

Is 
``` python
ctrl_spec = CtrlSpec(QBit(), cvs=0b0)
ctrl, q = bb.add(ZGate(), ctrl=ctrl, q=q)
```
preferred?

**Comment by mpharrigan** [comment]
sorry, I don't fully understand your code snippets. Where are you using the `ctrl_spec` in either of them?

```python
ctrl, q = bb.add(ZGate().controlled(), ctrl=ctrl, q=q)
```
would be how I would do it

**Comment by fdmalone** [comment]
I want an off-control.

**Comment by fdmalone** [comment]
Whoops, should have been:

``` python
ctrl_spec = CtrlSpec(cvs=[0])
(ctrl,), q = bb.add(ZGate().controlled(ctrl_spec), ctrl=(ctrl,), q=q)
```

and 

``` python
ctrl_spec = CtrlSpec(QBit(), cvs=0b0)
ctrl, q = bb.add(ZGate().controlled(ctrl_spec), ctrl=ctrl, q=q)
```

**Comment by mpharrigan** [comment]
So you want a one-bit off-control. In the first one, you have to wrap your `ctrl` soquet in a lengh-1-list, which seems wrong and annoying. In the second one, you have to specify `QBit()`. You'd prefer something where you can just put `cvs=0`? Is this a correct summary of the issue?

**Comment by fdmalone** [comment]
Right the second way seems a bit verbose. Very low priority though, just ran into it in #882

**Comment by mpharrigan** [comment]
Does it not work if you do `CtrlSpec(cvs=0)`? the default data type should be `QBit()`, no?
