### ISSUE TITLE
Move symolic counting utils somewhere more convenient

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#917]
These utils have no dependencies on any of the actual resource counting functionality and are currently hard to find burried deep within that package. There should probably be a top-level package that exports all of the functions and types. 

Additionally, we should make sure that all the "symbolic" versions of existing things have a distinct name. I think we've been pre-pending them with an "s".

Finally: a long term consideration would be whether we just drop the distinction between python/numpy/sympy and go full sympy everywhere (and then just use the sympy types and functions)

**Comment by tanujkhattar** [comment]
This is done by https://github.com/quantumlib/Qualtran/pull/941
