### ISSUE TITLE
 No '__dict__' attribute on 'CtrlSpec' instance to cache 'shapes' property.

### ISSUE THREAD

**Issue by lamq317** [quantumlib/Qualtran#948]
Hello,
I have installed the latest state of the main branch and wanted to define a controlled version of a Bloq, but ran into an error of the form: "No '__dict__' attribute on 'CtrlSpec' instance to cache 'shapes' property." when using show_bloq to visualize the controlled bloq. Indeed I tested one of the scripts that you have posted as part of the documentation:

from qualtran.bloqs.for_testing import TestAtom
atom = TestAtom()
catom = atom.controlled()
show_bloq(catom)

and got the same error. Here I am showing the last lines of the error when executing the script in a Jupyter notebook:
```
989 except AttributeError:  # not all objects have __dict__ (e.g. class defines slots)
    990     msg = (
    991         f"No '__dict__' attribute on {type(instance).__name__!r} "
    992         f"instance to cache {self.attrname!r} property."
    993     )
--> 994     raise TypeError(msg) from None
    995 val = cache.get(self.attrname, _NOT_FOUND)
    996 if val is _NOT_FOUND:

TypeError: No '__dict__' attribute on 'CtrlSpec' instance to cache 'shapes' property.
```

**Comment by mpharrigan** [comment]
what version of python are you using?

**Comment by mpharrigan** [comment]
my guess would be that this is some weird interplay between `cached_property` and the `attrs.frozen` class

**Comment by lamq317** [comment]
Thanks for your answer. Currently I am using Python 3.11.5, is there a particular version that you recommend? Thanks again!

**Comment by lamq317** [comment]
After upgrading my python version, my issue was solved. Thanks!

**Comment by mpharrigan** [comment]
Very strange ... it should work on python 3.11. Maybe it was the specific version of `attrs` or another dependency that was causing the issue.

**Comment by dstrain115** [comment]
I can reproduce it with python 3.11.8 and attrs==23.2.0

**Comment by mpharrigan** [comment]
I can't reproduce on python 3.11.7 or 3.11.8 with attrs 23.2.0 (arm mac; conda-forge build of python). It must be conflicting versions of something else.

@dstrain115 is it specifically with `CtrlSpec`? We use `@cached_property` with `@attrs.frozen` on nearly every bloq in the library.

**Comment by dstrain115** [comment]
I made a mistake and confused this with #955, which I reproduced.  I will try to reproduce this error in a bit.

**Comment by mpharrigan** [comment]
Closing as stale / could not reproduce
