### ISSUE TITLE
Unclear how to use symbolics

### ISSUE THREAD

**Issue by mstechly** [quantumlib/Qualtran#951]
I tried to create some bloqs with symbolic costs and it's unclear how exactly to do that.

Here's the numeric version:

```
from qualtran.bloqs.arithmetic.comparison import LessThanEqual
bloq = LessThanEqual(10, 15)
bloq.t_complexity()
```

This works well and returns: `TComplexity(t=96, clifford=533, rotations=0)`

However if I try the following:

```
from qualtran.bloqs.arithmetic.comparison import LessThanEqual
import sympy
a, b = sympy.symbols("a b")
bloq = LessThanEqual(a, b)
bloq.t_complexity()
```

I'm getting: `TypeError: cannot determine truth value of Relational`

Perhaps things are working properly and I'm just using them in a wrong way, but I also wanted to give you some feedback on how it looks like from a user's perspective :)  From reading the docs and tests I wasn't able to figure out how to make it work – I didn't see tests for symbolics for this bloq.

**Comment by mpharrigan** [comment]
Yes, only some bloqs support symbolic parameters but there's no way of (reliably) knowing which. Some fixes that we need

 - [ ] write a general docs page about symbolics support and how it's up to the bloq to make it work or not
 - [ ] update type annotations and arg docstrings to make it clear which parameters can be symbolic
 - [ ] make more things support symbolic parameters

**Comment by mstechly** [comment]
Can you tell me which bloqs do support it, just so I have some examples to work with for now :) ?

**Comment by tanujkhattar** [comment]
qrom supports it after https://github.com/quantumlib/Qualtran/pull/945

**Comment by mstechly** [comment]
Thanks @tanujkhattar, now this works properly!

```
import sympy
N, M, b1, b2, c = sympy.symbols('N M b1 b2 c')
qrom_symb = QROM.build_from_bitsize((N, M), (b1, b2), num_controls=c)
qrom_symb.t_complexity()
```

`TComplexity(t=4*M*N + 4*c - 8, clifford=M*N*b1*b2 + 13*M*N + 13*c - 26, rotations=0)` 
:) 

However,  while I can decompose a numeric bloq, I can't decompose a symbolic one:

```
import sympy
N, M, b1, b2, c = sympy.symbols('N M b1 b2 c')
qrom_symb = QROM.build_from_bitsize((N, M), (b1, b2), num_controls=c)
qrom_symb.decompose_bloq()
```

```
*** qualtran._infra.bloq.DecomposeTypeError: Cannot decompose parameterized QROM(data_or_shape=Shaped(shape=(2, N, M)), selection_bitsizes=(ceiling(log2(N - 1)), ceiling(log2(M - 1))), target_bitsizes=(b1, b2), num_controls=c).
```

**Comment by mpharrigan** [comment]
Discussed offline: but state prep alias sampling should be able to do one level of decomposition since the symbolic bitsizes of all the wires are preserved. 

Decomposing a qrom circuit with symbolic size is not possible since we need to split symbolically-sized registers into a concrete number of qubit wires

One can use the call graph protocol to get callees without knowing exactly how they're wired up
