### ISSUE TITLE
Bloq modules missing autodocs

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#978]
# Basic gates
- [ ] [y_gate.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./basic_gates/y_gate.py)
- [ ] [on_each.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./basic_gates/on_each.py)
# Factoring
- [ ] [mod_sub.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./factoring/mod_sub.py)
- [ ] [_ecc_shims.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./factoring/ecc/_ecc_shims.py)
- [ ] [ec_point.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./factoring/ecc/ec_point.py)
- [x] [reflection_using_prepare.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./reflection_using_prepare.py)

# Mod arithmetic
- [ ] [_shims.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./mod_arithmetic/_shims.py)
# Multiplexers
- [ ] [unary_iteration_bloq.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./multiplexers/unary_iteration_bloq.py)
- [ ] [selected_majorana_fermion.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./multiplexers/selected_majorana_fermion.py)
# Arithmetic
- [ ] [_shims.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./arithmetic/_shims.py)
- [ ] [hamming_weight.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./arithmetic/hamming_weight.py)
# Chemistry
- [ ] [black_boxes.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/black_boxes.py)
- [ ] [chem_tutorials.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/chem_tutorials.py)
- [ ] [prepare.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/sf/prepare.py)
- [ ] [select_bloq.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/sf/select_bloq.py)
- [ ] [hamiltonian.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/ising/hamiltonian.py)
- [ ] [walk_operator.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/sparse/walk_operator.py)
- [ ] [walk_operator.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/thc/walk_operator.py)
- [ ] [notebook_utils.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/thc/notebook_utils.py)
- [ ] [trotter_step.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/trotter/hubbard/trotter_step.py)
- [ ] [prepare.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/df/prepare.py)
- [ ] [select_bloq.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/df/select_bloq.py)
- [ ] [prepare_t.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/projectile/prepare_t.py)
- [ ] [prepare_uv.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/projectile/prepare_uv.py)
- [ ] [select_uv.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/projectile/select_uv.py)
- [ ] [select_t.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/projectile/select_t.py)
- [ ] [prepare_nu.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/projectile/prepare_nu.py)
- [ ] [prepare_zeta.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/prepare_zeta.py)
- [ ] [prepare.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/prepare.py)
- [ ] [prepare_nu.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./chemistry/pbc/first_quantization/prepare_nu.py)
# Utilities
- [ ] [util_bloqs.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./util_bloqs.py)
# QFT
- [ ] [qft_phase_gradient.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./qft/qft_phase_gradient.py)
- [ ] [qft_text_book.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./qft/qft_text_book.py)
# Select and Prepare
- [ ] [select_and_prepare.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./select_and_prepare.py)
# Mean Estimation
- [ ] [mean_estimation_operator.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./mean_estimation/mean_estimation_operator.py)
- [ ] [arctan.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./mean_estimation/arctan.py)
- [ ] [complex_phase_oracle.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./mean_estimation/complex_phase_oracle.py)
# Rotations
- [ ] [phase_gradient.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./rotations/phase_gradient.py)
- [ ] [hamming_weight_phasing.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./rotations/hamming_weight_phasing.py)
- [ ] [programmable_rotation_gate_array.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./rotations/programmable_rotation_gate_array.py)
# Datat Loading
- [ ] [select_swap_qrom.py](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/./data_loading/select_swap_qrom.py)

**Comment by fdmalone** [comment]
cc @mpharrigan

**Comment by mpharrigan** [comment]
lets exclude the `for_testing` bloqs. I don't think those should be included in the web docs

**Comment by mpharrigan** [comment]
qft is tracked in #952

**Comment by fdmalone** [comment]
Jenky bash script

``` bash
#!/bin/bash

CLASS_NAME="BloqDocSpec"  # Replace with the actual class name

find . -name "**.py" -not -name "__init__.py" -not -name "*_test.py" -print0 | while IFS= read -r -d $'\0' file; do
    if ! grep -q "$CLASS_NAME" "$file"; then
        echo  "- [ ] [$(basename $file)](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/$file)"
    fi
done
```

**Comment by mpharrigan** [comment]
you can also use dev_tools/bloq_report_card

**Comment by fdmalone** [comment]
I forgot 🤦 , also incomplete since it only checks if there are no imports of BloqDocSpec if a module defines more than one bloq
