### ISSUE TITLE
Organize remaining bloqs in bloqs

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#979]
- [ ] block_endoding, qubitization_walk_operator and reflection, select_and_prepare -> something to do with qubitization OR block _encoding should live by itself, reflection will probably be deprecated #966 
- [ ] on_each.ipynb -> basic_gates
- [ ] hubbard_model -> chemistry?
- [ ] util_bloqs -> utilities (@mpharrigan rename utils?)

**Comment by mpharrigan** [comment]
utils should be "bookkeeping"

**Comment by fdmalone** [comment]
chemistry should maybe be further organized as chemistry/qubitization and chemistry/trotter
