### ISSUE TITLE
Title boxes for OnEach bloq are broken

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#990]
#956 removed titles from single qubit gates but this means on each now renders like:

<img width="234" alt="Screenshot 2024-05-23 at 9 34 53 AM" src="https://github.com/quantumlib/Qualtran/assets/12097876/719e36f4-1cbf-48e0-a879-66d45252b3b4">

Is the solution here to just say goodbye to $H^{\otimes N}$

**Comment by mpharrigan** [comment]
OnEach's wire_symbol method must be updated. The title text should be removed and the wire symbol can use either `str(self.gate)` or `self.gate.wire_symbol(Register('q', QBit()))`.

**Comment by fdmalone** [comment]
Maybe I'm missing something but the state of affairs is a little odd:

<img width="299" alt="Screenshot 2024-05-28 at 9 36 35 AM" src="https://github.com/quantumlib/Qualtran/assets/12097876/7c84c6d4-5993-47b8-880e-017d06019e64"> <--- shouldn't have a title but does?
<img width="280" alt="Screenshot 2024-05-28 at 9 36 40 AM" src="https://github.com/quantumlib/Qualtran/assets/12097876/718f2cb8-02d6-42ca-a595-055287c1d1e9"> <--- looks fine
<img width="563" alt="Screenshot 2024-05-28 at 9 37 29 AM" src="https://github.com/quantumlib/Qualtran/assets/12097876/7e07fb2c-3918-4b49-9e64-ed2e97d1cb87"> <--- show_bloq now has no information, musical score looks ok.

**Comment by fdmalone** [comment]
I know the XGate got missed in #956 but having show_bloq without any bloq information seems wrong?

**Comment by fdmalone** [comment]
Should we be doing:

```
diff --git a/qualtran/drawing/graphviz.py b/qualtran/drawing/graphviz.py
index 281571e1..54a46a33 100644
--- a/qualtran/drawing/graphviz.py
+++ b/qualtran/drawing/graphviz.py
@@ -377,7 +377,9 @@ class PrettyGraphDrawer(GraphDrawer):
         if isinstance(binst.bloq, (Split, Join)):
             return ''
         # This wire symbol should always be a text element
-        wire_symbol_title = binst.bloq.wire_symbol(reg=None).text  # type: ignore[attr-defined]
+        wire_symbol_title = str(
+            binst.bloq
+        )  # binst.bloq.wire_symbol(reg=None).text  # type: ignore[attr-defined]
         if not wire_symbol_title:
             return ''
         return f'<font point-size="10">{html.escape(wire_symbol_title)}</font>'
```

Is this part of a larger issue @mpharrigan

**Comment by dstrain115** [comment]
This is probably because I was not clear exactly how these are rendering and screwed up the refactor.  Can you help fix it?

**Comment by fdmalone** [comment]
Sure yeah, I'm not sure what the state of `bloq.__str__` is, so I'll hold off for confirmation before fixing things whole sale.

**Comment by fdmalone** [comment]
@mpharrigan should this go in before release?

**Comment by mpharrigan** [comment]
I'll take this
